/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/charlote.glb --transform 
Files: public/models/charlote.glb [33.11MB] > /home/bluemoon/Learning/Code/JavaScript/THREE/boilerthreejs/charlote-transformed.glb [2.19MB] (93%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/charlote-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane008.geometry} material={materials.Material} position={[-0.675, 0.214, 0.221]} rotation={[Math.PI / 2, 0, 0]} scale={0.68} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.stone1} position={[0.027, 1.402, -0.154]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.004']} position={[0.016, 0.214, -0.81]} />
    </group>
  )
}

useGLTF.preload('/charlote-transformed.glb')
