/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/untitled.gltf -o src/components/Charlotte.jsx -k -K -r public
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/untitled.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials['Material.001']} position={[-0.67, 0.21, 0.22]} rotation={[Math.PI / 2, 0, 0]} scale={0.68} />
        <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials['Material.001']} position={[1.03, 0.21, -0.18]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.68} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials.stone1} position={[0.03, 1.4, -0.15]} />
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.004']} position={[0.02, 0.21, -0.81]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/untitled.gltf')
